"use client";

import React from "react";

export default function PrivacyPolicyPage() {
    return (
        <div className="flex flex-col min-h-screen items-center justify-center bg-zinc-50 dark:bg-black font-sans p-4">
            <main className="w-full max-w-3xl flex flex-col items-center bg-white dark:bg-neutral-900 shadow-xl rounded-2xl p-8 sm:p-12 mt-12 mb-12">
                <h1 className="text-4xl font-extrabold text-center mb-4 tracking-tight bg-gradient-to-r from-purple-600 via-pink-500 to-red-400 text-transparent bg-clip-text">
                    Privacy Policy
                </h1>
                <p className="text-sm text-gray-500 mb-2 text-center">Last updated: May 12, 2026</p>
                <div className="prose prose-sm sm:prose-base dark:prose-invert w-full">
                    <p>
                        This Privacy Policy describes our policies and procedures on the collection,
                        use, and disclosure of your information when you use viaEngage (the "Service")
                        and tells you about your privacy rights and how the law protects you.
                    </p>
                    <p>
                        We use your personal data to provide and improve viaEngage. By using the Service,
                        you agree to the collection and use of information in accordance with this Privacy Policy.
                    </p>

                    <h2>Interpretation and Definitions</h2>
                    <h3>Interpretation</h3>
                    <p>
                        The words with initial capital letters have meanings defined under the following conditions.
                        The following definitions shall have the same meaning regardless of whether they appear in
                        singular or plural.
                    </p>
                    <h3>Definitions</h3>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul>
                        <li>
                            <strong>Account</strong> means a unique account created for you to access our Service or parts of our Service.
                        </li>
                        <li>
                            <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares or other securities entitled to vote for election of directors or other managing authority.
                        </li>
                        <li>
                            <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to viaEngage.
                        </li>
                        <li>
                            <strong>Cookies</strong> are small files placed on your device by a website, containing the details of your browsing history on that website among other uses.
                        </li>
                        <li>
                            <strong>Country</strong> refers to: India
                        </li>
                        <li>
                            <strong>Device</strong> means any device that can access the Service such as a computer, cellphone, or digital tablet.
                        </li>
                        <li>
                            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
                        </li>
                        <li>
                            <strong>Service</strong> refers to viaEngage website and platform.
                        </li>
                        <li>
                            <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed to facilitate the Service, provide the Service on our behalf, perform services related to the Service, or assist us in analyzing how the Service is used.
                        </li>
                        <li>
                            <strong>Third-party Social Media Service</strong> refers to any website or social network website through which a User can log in or create an account to use the Service.
                        </li>
                        <li>
                            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, duration of a page visit).
                        </li>
                        <li>
                            <strong>Website</strong> refers to viaEngage website, accessible from our official URL.
                        </li>
                        <li>
                            <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on whose behalf such individual is accessing or using the Service, as applicable.
                        </li>
                    </ul>

                    <h2>Collecting and Using Your Personal Data</h2>
                    <h3>Types of Data Collected</h3>
                    <h4>Personal Data</h4>
                    <p>
                        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:
                    </p>
                    <ul>
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Phone number</li>
                        <li>Address, State, Province, ZIP/Postal code, City</li>
                        <li>Usage Data</li>
                    </ul>
                    <h4>Usage Data</h4>
                    <p>
                        Usage Data is collected automatically when using the Service. Usage Data may include information such as your Device’s Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.
                    </p>
                    <p>
                        When you access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                    </p>
                    <p>
                        We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device.
                    </p>

                    <h4>Information from Third-Party Social Media Services</h4>
                    <p>
                        viaEngage allows you to create an account and log in to use the Service through the following Third-party Social Media Services:
                    </p>
                    <ul>
                        <li>Google</li>
                        <li>Facebook</li>
                        <li>Instagram</li>
                        <li>Twitter</li>
                        <li>LinkedIn</li>
                    </ul>
                    <p>
                        If you register through or grant us access to a Third-Party Social Media Service, we may collect Personal Data already associated with your third-party social media account, such as your name, email address, and other details described by the social media provider.
                    </p>

                    <h4>Tracking Technologies and Cookies</h4>
                    <p>We use Cookies and similar tracking technologies to track the activity on our Service and store certain information. These include:</p>
                    <ul>
                        <li>
                            <strong>Cookies or Browser Cookies:</strong> Small files placed on your device. You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, some parts of our Service may be unavailable.
                        </li>
                        <li>
                            <strong>Web Beacons:</strong> Small electronic files permitting the counting of users and other related statistics.
                        </li>
                    </ul>
                    <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your device when you go offline, while Session Cookies are deleted as soon as you close your browser.</p>
                    <p>We use both types of Cookies for various legitimate purposes, such as providing Service functionality, remembering preferences, and measuring effectiveness of our communication.</p>

                    <h3>Use of Your Personal Data</h3>
                    <p>We may use Personal Data for the following purposes:</p>
                    <ul>
                        <li>To provide and maintain our Service</li>
                        <li>To manage your Account and registration</li>
                        <li>For performance of contracts entered with you</li>
                        <li>To contact you about updates, security, and features of the Service</li>
                        <li>To provide you with news, offers, and general information about goods and services similar to those you already use</li>
                        <li>To manage your requests</li>
                        <li>For business transfers (e.g., mergers or acquisitions)</li>
                        <li>For other legitimate business uses such as analysis, product improvement, etc.</li>
                    </ul>
                    <p>We may share your personal information with Service Providers, Affiliates, business partners, other users (as described), or with your consent.</p>

                    <h3>Retention of Your Personal Data</h3>
                    <p>
                        We will retain your Personal Data only as long as necessary for the purposes outlined in this Privacy Policy, to comply with legal obligations, resolve disputes, and enforce agreements.
                    </p>

                    <h3>Transfer of Your Personal Data</h3>
                    <p>
                        Your information may be transferred to – and maintained on – servers located outside your state/province/country. Your submission of such information represents your agreement to that transfer and processing.
                    </p>

                    <h3>Delete Your Personal Data</h3>
                    <p>
                        You have the right to request deletion of your Personal Data. You may update, amend, or delete your information at any time or contact us via the methods below.
                        We may, however, retain certain information when required by law or where we have a lawful basis to do so.
                    </p>

                    <h3>Disclosure of Your Personal Data</h3>
                    <ul>
                        <li>
                            <strong>Business Transactions:</strong> If viaEngage is involved in a merger, acquisition, or asset sale, your personal data may be transferred. We will notify you before such transfer.
                        </li>
                        <li>
                            <strong>Law Enforcement:</strong> We may disclose your Personal Data if required by law or in response to valid public authority requests.
                        </li>
                        <li>
                            <strong>Other Legal Requirements:</strong> We may disclose your Personal Data in good faith where necessary to:
                            <ul className="ml-4">
                                <li>Comply with a legal obligation</li>
                                <li>Protect the rights or property of viaEngage</li>
                                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                                <li>Protect the personal safety of users or the public</li>
                                <li>Protect against legal liability</li>
                            </ul>
                        </li>
                    </ul>

                    <h3>Security of Your Personal Data</h3>
                    <p>
                        We use commercially acceptable means to protect your data, but no method of transmission or electronic storage is 100% secure.
                    </p>

                    <h3>Children’s Privacy</h3>
                    <p>
                        Our Service does not address anyone under the age of 13. We do not knowingly collect personal information from anyone under 13. If you are a parent or guardian and believe your child has provided us data, please contact us so we can take appropriate action.
                    </p>

                    <h3>Links to Other Websites</h3>
                    <p>
                        Our Service may contain links to other websites. If you click on a third-party link, you will be directed to their site. We strongly advise reviewing the Privacy Policy of every site you visit. We have no control over and assume no responsibility for privacy practices of third-party sites.
                    </p>

                    <h3>Changes to this Privacy Policy</h3>
                    <p>
                        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the "Last updated" date. You are advised to review this page periodically for any changes.
                    </p>

                    <h3>Contact Us</h3>
                    <p>
                        If you have any questions about this Privacy Policy, you can contact us:
                    </p>
                    <ul>
                        <li>By email: <a href="mailto:rudrakshkachhawa@gmail.com">rudrakshkachhawa@gmail.com</a></li>
                        {/* You can replace the URL below with your own contact page */}
                        <li>By visiting this page on our website: <a href="https://via-engage-fe.vercel.app/contact-us" target="_blank" rel="noopener noreferrer">https://via-engage-fe.vercel.app/contact-us</a></li>
                    </ul>
                </div>
            </main>
        </div>
    );
}